# -*- coding: utf-8 -*-
"""traductor_de_numeros.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tmXsmk9-ceVLQEIoRR-VLyZoRDLdycjo

# Programa para traducir números del 1 al 10 al inglés
# Solicita un número al usuario y lo convierte en un entero

# Evalúa el número ingresado y muestra la traducción en inglés
"""

numero = int(input("Ingresa un número del 1 al 10: "))
if numero == 1:
    print("One")  # Uno
elif numero == 2:
    print("Two")  # Dos
elif numero == 3:
    print("Three")  # Tres
elif numero == 4:
    print("Four")  # Cuatro
elif numero == 5:
    print("Five")  # Cinco
elif numero == 6:
    print("Six")  # Seis
elif numero == 7:
    print("Seven")  # Siete
elif numero == 8:
    print("Eight")  # Ocho
elif numero == 9:
    print("Nine")  # Nueve
elif numero == 10:
    print("Ten")  # Diez
else:
    # Si el número no está en el rango del 1 al 10, muestra un mensaje de error
    print("Número fuera del rango permitido")