# -*- coding: utf-8 -*-
"""calculadora_IMC_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kVlYzqwXXf2KSGcFsvme3PXU-mMcP-Gu

## Proyecto Arukay: Cálculo del Índice de Masa Corporal (IMC)

### Descripción
El Índice de Masa Corporal (IMC) es un indicador utilizado para evaluar si una persona tiene un peso saludable en relación con su altura. Se calcula dividiendo el peso en kilogramos entre el cuadrado de la altura en metros. Este proyecto permite calcular el IMC de un usuario y determinar si se encuentra dentro del rango saludable según los estándares de la Organización Mundial de la Salud (OMS).

### Objetivos
1. Solicitar al usuario su altura y peso.
2. Calcular el IMC utilizando la fórmula establecida.
3. Definir el rango de IMC considerado saludable.
4. Verificar si el IMC del usuario está dentro del rango saludable.
5. Proporcionar un mensaje con los resultados y recomendaciones.
"""

# Paso 1. Solicitar al usuario que ingrese su altura en metros y su peso en kilogramos
# Guardamos los valores en variables diferentes

altura = float(input("Ingrese su altura en metros: "))  # Solicitamos la altura y convertimos a float
peso = float(input("Ingrese su peso en kilogramos: "))  # Solicitamos el peso y convertimos a float

# Paso 2. Calcular el IMC utilizando la fórmula: IMC = peso / (altura * altura)

imc = peso / (altura ** 2)  # Fórmula del IMC

# Paso 3. Definir los rangos saludables de IMC

rango_saludable_min = 18.5
rango_saludable_max = 24.9

# Paso 4. Comprobar si el IMC calculado se encuentra dentro del rango saludable

en_rango_saludable = rango_saludable_min <= imc <= rango_saludable_max

# Mostrar resultados
print(f"Su IMC es: {imc:.2f}")
print(f"¿Está dentro del rango saludable? {en_rango_saludable}")

# Explicación del resultado
if en_rango_saludable:
    print("Su peso está equilibrado respecto a su altura.")
else:
    print("Su peso puede estar fuera del rango saludable. Considere consultar con un profesional de la salud.")

"""### Resultados esperados
El usuario ingresará su peso y altura, y el sistema calculará su IMC. Luego, el programa indicará si el IMC se encuentra dentro del rango saludable (18.5 - 24.9) o si está fuera de este, recomendando acudir a un profesional de la salud en caso necesario.

### Conclusiones
- El IMC es una herramienta útil para evaluar el peso corporal en relación con la altura.
- Sin embargo, el IMC no tiene en cuenta la composición corporal, por lo que debe complementarse con otras evaluaciones médicas.
- Mantener un IMC dentro del rango saludable puede reducir el riesgo de enfermedades relacionadas con el peso, como la obesidad o la desnutrición.

### Referencia
Organización Mundial de la Salud (OMS). "Índice de Masa Corporal (IMC)". Disponible en: [https://www.who.int/news-room/fact-sheets/detail/obesity-and-overweight](https://www.who.int/news-room/fact-sheets/detail/obesity-and-overweight)

"""