# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t23qs6Mp4h6hBP1h60iKjHutt5Ll9Ya1
"""

# Solicitar el nombre completo del usuario
nombre_completo = input("Ingresa tu nombre completo: ")

# Convertir el nombre completo a minúsculas
nombre_completo = nombre_completo.lower()

# Dividir el nombre completo en palabras
palabras_nombre = nombre_completo.split()

# Obtener el primer nombre
primer_nombre = palabras_nombre[0]

# Obtener la inicial del primer nombre
inicial_primer_nombre = primer_nombre[0]

# Calcular la longitud del nombre completo
longitud_nombre = len(nombre_completo)

# Reemplazar espacios por guiones bajos
nombre_formateado = nombre_completo.replace(" ", "_")

# Imprimir los resultados
print("Nombre completo en minúsculas:", nombre_completo)
print("Primer nombre:", primer_nombre)
print("Inicial del primer nombre:", inicial_primer_nombre)
print("Longitud del nombre completo:", longitud_nombre)
print("Nombre formateado:", nombre_formateado)