# -*- coding: utf-8 -*-
"""sesion_8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PP1sfua8FPMTy9gAg2c2WDlGdQaBuWt_

# Este ejemplo demuestra el uso de estructuras condicionales anidadas en Python
 para simular un menú interactivo de comida o bebida. El objetivo es desarrollar
 habilidades de control de flujo y entrada de datos del usuario.

 Autor: Sara Leon

 Fecha: 04/04/2025

 Título: Menú de comida o bebida con condicionales en Python
"""

# Se solicita al usuario que indique si desea almuerzo o bebida.
preferencia = input("¿Prefieres 'almuerzo' o 'bebida'? ").lower()

# Evaluamos la elección del usuario
if preferencia == "almuerzo":
    # Menú de carnes
    carne = input("Elige una carne: 'carne', 'pollo', o 'pescado': ").lower()

    if carne == "carne":
        preparacion = input("¿Cómo deseas la carne? 'asada' o 'guisada': ").lower()
        if preparacion in ["asada", "guisada"]:
            print(f"Has elegido carne {preparacion}.")
        else:
            print("Lo sentimos, no tenemos esa opción de preparación.")

    elif carne == "pollo":
        preparacion = input("¿Cómo deseas el pollo? 'frito' o 'horneado': ").lower()
        if preparacion in ["frito", "horneado"]:
            print(f"Has elegido pollo {preparacion}.")
        else:
            print("Lo sentimos, no tenemos esa opción de preparación.")

    elif carne == "pescado":
        preparacion = input("¿Cómo deseas el pescado? 'empanizado' o 'al vapor': ").lower()
        if preparacion in ["empanizado", "al vapor"]:
            print(f"Has elegido pescado {preparacion}.")
        else:
            print("Lo sentimos, no tenemos esa opción de preparación.")

    else:
        print("Lo sentimos, no tenemos esa carne en el menú.")

elif preferencia == "bebida":
    bebida = input("Elige una bebida: 'jugo', 'soda' o 'agua': ").lower()

    if bebida == "jugo":
        fruta = input("¿De qué fruta deseas el jugo? 'naranja', 'piña' o 'fresa': ").lower()
        if fruta in ["naranja", "piña", "fresa"]:
            print(f"Has elegido jugo de {fruta}.")
        else:
            print("Lo sentimos, no tenemos esa fruta para el jugo.")

    elif bebida == "soda":
        tipo_soda = input("¿Qué soda deseas? 'cola', 'limón' o 'naranja': ").lower()
        if tipo_soda in ["cola", "limón", "naranja"]:
            print(f"Has elegido soda sabor {tipo_soda}.")
        else:
            print("Lo sentimos, no tenemos esa soda.")

    elif bebida == "agua":
        tipo_agua = input("¿Qué tipo de agua deseas? 'natural', 'con gas' o 'con limón': ").lower()
        if tipo_agua in ["natural", "con gas", "con limón"]:
            print(f"Has elegido agua {tipo_agua}.")
        else:
            print("Lo sentimos, no tenemos esa agua disponible.")

    else:
        print("Lo sentimos, no tenemos esa opción de bebida.")

else:
    print("Opción no válida. Por favor elige entre 'almuerzo' o 'drink'.")